version: "3.3"

services:
    nginx:
            env_file:
                    - ./.env
            image: nginx:${NGINX_VERSION}-alpine
            container_name: nginx
            volumes:
                    - ${WEB_ROOT_DIR}:/usr/share/nginx/html:rw
                    - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
                    - ${NGINX_CONF_DIR}:/etc/nginx/conf.d/:ro
                    - ${NGINX_SSL_CERTS_DIR}:/etc/nginx/certs/:ro
                    - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
                    - ${CERTBOT_CONF_DIR}:/etc/letsencrypt/:rw
            networks:
                    - lnmp-nginx
                    - lnmp-php
            ports:
                    - "${NGINX_HTTP_HOST_PORT}:80"
                    - "${NGINX_HTTPS_HOST_PORT}:443"
            links:
                    - php
            depends_on:
                    - php
            restart:
                    always
    php:
            env_file:
                    - ./.env
            build:
                context: ./php-fpm
                args:
                    PHP_VERSION: ${PHP_VERSION}
                    PHP_EXTENSIONS: ${PHP_EXTENSIONS}
            container_name: php
            volumes:
                    - ${WEB_ROOT_DIR}:/usr/share/nginx/html:rw
                    - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
                    - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
                    - ${PHP_LOG_DIR}:/var/log/:rw
            networks:
                    - lnmp-php
                    - lnmp-mysql
                    - lnmp-redis
            ports:
                    - "9000"
            links:
                    - mysql
                    - redis
            depends_on:
                    - mysql
            restart:
                    always
    mysql:
            env_file:
                    - ./.env
            image: mysql:${MYSQL_VERSION}
            container_name: mysql
            volumes:
                    - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
                    - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw
                    - ${MYSQL_LOG_DIR}:/var/log/mysql:rw
            networks:
                    - lnmp-mysql
            ports:
                    - "${MYSQL_HOST_PORT}:3306"
            environment:
                    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
                    - MYSQL_USER=${MYSQL_USER_NAME}
                    - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
                    - TZ=Asia/Shanghai
            command: ['mysqld', '--character-set-server=utf8mb4']
            restart:
                    always
    redis:
            env_file:
                    - ./.env
            image: redis:${REDIS_VERSION}-alpine
            command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASS_WORD}"]
            container_name: redis
            volumes:
                    - ${REDIS_DATA_DIR}:/data:rw
            networks:
                    - lnmp-redis
            ports:
                    - "${REDIS_HOST_PORT}:6379"
            restart:
                    always
    certbot:
            env_file:
                    - ./.env
            image: certbot/certbot
            container_name: certbot
            volumes:
                    - ${CERTBOT_CONF_DIR}:/etc/letsencrypt/:rw
                    - ${CERTBOT_WORK_DIR}:/var/lib/letsencrypt:rw
                    - ${CERTBOT_LOG_DIR}:/var/log/letsencrypt/:rw
                    - ${WEB_ROOT_DIR}:/usr/share/nginx/html:rw
            depends_on:
                    - nginx
            networks:
                    - lnmp-php
networks:
    lnmp-nginx:
    lnmp-php:
    lnmp-mysql:
    lnmp-redis: