version: "3.3"

services:
    nginx:
            env_file:
                    - ./.env
            image: nginx:${NGINX_VERSION}-alpine
            container_name: nginx
            volumes:
                    - ${WEB_ROOT_DIR}:/usr/share/nginx/html:rw
                    - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
                    - ${NGINX_CONF_DIR}:/etc/nginx/conf.d/:ro
                    - ${NGINX_SSL_CERTS_DIR}:/etc/nginx/certs/:ro
                    - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
                    - ${CERTBOT_CONF_DIR}:/etc/letsencrypt/:rw
            networks:
                    - lnmp-nginx
            ports:
                    - "${NGINX_HTTP_HOST_PORT}:80"
                    - "${NGINX_HTTPS_HOST_PORT}:443"
            restart:
                    always
    certbot-toy:
            env_file:
                    - ./.env
            build:
                context: ./certbot
                args:
                    PHP_VERSION: ${PHP_VERSION}
                    PHP_EXTENSIONS: ${PHP_EXTENSIONS}
            image: certbot/certbot
            container_name: certbot-toy
            volumes:
                    - ${CERTBOT_CONF_DIR}:/etc/letsencrypt/:rw
                    - ${CERTBOT_WORK_DIR}:/var/lib/letsencrypt:rw
                    - ${CERTBOT_LOG_DIR}:/var/log/letsencrypt/:rw
                    - ${WEB_ROOT_DIR}:/usr/share/nginx/html:rw
            depends_on:
                    - nginx
            networks:
                    - lnmp-nginx
networks:
    lnmp-nginx:
